info:
  name: "SAP_BASIS_SYSTEM_CONFIG_CHECK :: STC_TM_SESSION_RESUME"
  type: http
  seq: 2

http:
  method: POST
  url: "{{protocol}}://{{host}}:{{port}}/sap/opu/odata/sap/ZSTC_TM_TASKLIST_SRV/SessionSet"
  headers:
    - name: Content-Type
      value: application/json
  body:
    type: json
    data: |-
      {
        "CallerInfo": {},
        "ExecSettings": {
          "Checkrun": false,
          "Batch": "X",
          "Async": false,
          "Trace": false,
          "BatchTarget": "S4DAPP01"
        },
        "ScenarioId": "",
        "TemplateId": "",
        "InitOnly": true,
        "IgnoreLanguDiff": true,
        "IgnoreScenarioDiff": true,
        "IgnoreScenarioObsolete": true,
        "Status": "0009",
        "StatusDescr": "Waiting to be executed",
        "Finalized": "@",
        "ExecId": "0.0000000",
        "SessionId": "SAP_BASIS_SYSTEM_CONFIG_CHECK_20260824075110598",
        "ToTaskParameter": [
          {
            "Definition": {
              "Taskname": "CL_STCT_CHECK_TMS",
              "Lnr": 1,
              "Fieldname": "P_OPT2",
              "Mandatory": false,
              "Datatype": "CHAR",
              "Leng": "000001",
              "Decimals": "000000",
              "Lowercase": false,
              "Outputlen": "000001",
              "Signflag": false,
              "Convexit": "",
              "Ddtext": "Error",
              "Password": false,
              "ReadOnly": false,
              "Checkbox": false,
              "Radiobutton": true,
              "RbGroup": "ICM",
              "Defaultval": ""
            },
            "Value": {
              "Taskname": "CL_STCT_CHECK_TMS",
              "Lnr": 1,
              "Fieldname": "P_OPT2",
              "Value": ""
            },
            "SessionId": "SAP_BASIS_SYSTEM_CONFIG_CHECK_20260824075110598",
            "ScenarioId": "SAP_BASIS_SYSTEM_CONFIG_CHECK",
            "TemplateId": ""
          }
        ]
      }
  auth: inherit

runtime:
  scripts:
    - type: before-request
      code: req.setHeader("x-csrf-token", bru.getCollectionVar("CSRF-TOKEN"))

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
  forwardAuthorizationHeader: false

docs: <br/>
